### ISSUE TITLE
Message for you

### ISSUE THREAD

**Issue by Zellix67** [dawg1337/FiveM_Codeine#1]
To begin, I would like to tell you that your message really touched me: "Maybe one day I will be important to everyone ...."

I would really like to start some serious projects and my intuition tells me that I should start with you, I don't know why, so I'll try my luck, here is my discord if ever: Zellix#2733

**Comment by SadraKhorami** [comment]
Very impressive 😆

**Comment by dawg1337** [comment]
**Added** 

<sup>Best regards ***dawg***</sup>

**Comment by Ezriral** [comment]
Wish you a good day even its abit late after i saw what you wrote in the code.

When i was reading it i really thought "wow im not the only one".

idk what problems you face but i guess its a bit similar to what i had, what did help me? i tried to improve myself.
if you poor earn more money, and by coding there is always a good way to earn money.
you are fat do sport.

what i wanna say is dont let the devil eat you. 

fuck, tears in my eyes, fucking memories...

have a good one.

**Comment by dawg1337** [comment]
Ye i reliased that back in 2022 i am the best version of me that i could possibly ever be. Im rock solid intelligent and not using my computer anymore which is also why i havent answered theese comments lol.

**Comment by Zellix67** [comment]
I think I have also become a better version of myself and I have become much more open to the world in this year 2023, for me 2022 was a great year despite all the trials I had to go through. Life is sometimes very cruel but also very beautiful I think you have to enjoy the balance.

Hoping that 2023 will be our year, I wish you a lot of success and we will meet again soon :)

**Comment by dawg1337** [comment]
fr i'm now back at my computer cuszi have to study so i though it would start gamehacking again lol
